export const campusList = [
  "Guru Nanak Dev DSEU Campus",
  "Meerabai DSEU Campus",
  "Ambedkar DSEU Campus",
  "DSEU Vivek Vihar Campus",
  "DSEU Mayur Vihar Campus",
  "Aryabhat DSEU Campus",
  "Kasturba DSEU Campus",
  "DSEU Wazirpur Campus",
  "DSEU Dheerpur Campus",
  "GB Pant DSEU Campus",
  "CHAMPS DSEU",
  "DSEU Pusa II Building",
  "DSEU Rajokri Campus",
  "DSEU Siri Fort Campus",
  "DSEU Dwarka Campus",
  "DSEU Ranhola Campus",
  "DSEU Jaffarpur Campus",
  "DSEU Okhla Campus",
  "DSEU Pusa I Campus",
  "DSEU Jhandewalan Campus",
  "DSEU Okhla-II Campus",
  "Bhai Paramanand DSEU Campus"
];
