export const RoleRoutes = {
  admin: ["/admin/dashboard"],
  superadmin: [
    "/vc-dashboard",
    "/attendance",
    "/weekly-report",
    "/monthly-report",
    "/track-leave",
    "/leave-details/:id",
    "/track-leave/history",
    "/announcements",
    "/announcement/:id",
    "/post",
    "/attach-link",
    "/schedule",
    "/holidays",
    "/campus",
    "/campus/:id",
    "/profile",
    "/profile/:employeeId",
    "/employee-details/:employeeId",
    "/inventory",
    "/surveillance",
    "/officer-details/:id",
    "/employees",
    "/calendar",
  ],
  employee: ["/employee-dashboard", "/employee-leave", "/employee-announcements"],
};
